server:
  port: 8001
spring:
  datasource:
    username: root
    password: 3418972095
    url: jdbc:mysql://localhost:3306/ordering_system?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    format:
      time: HH:mm:ss
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    cache: false

  mail:
    host: smtp.qq.com
    username: 941728409@qq.com
    password: jwmxtipnddkobajg
    properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
           required: true
#整合Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml    #指定下面的xml路径
  type-aliases-package: com.web.entity   # 注意对应实体类的路径  配置包扫描的别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页插件
pagehelper:
  helper-dialect: mysql
  params: countSql
  reasonable: true
  support-methods-arguments: true

alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000121603966
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfgIcgsrBTnou2C2wgcb5682xHb0N5xv8XIsSsnVm7Z+mWaJdLf17E+I+92XOQi7nwefcXapiE6NCnciTeRJ8io3W+God+N+tKwmeEuizREBeCBdjd3no32f0QZA7xI6W8F+NfEQXEaEe/r2zGnKmUBpN3tUA830sqrl8hDEbYTSt9mmQwPgDrDYa28NL/yHPv+mgmjCp8Ue3xk5DpkKOEIjOWP3rKgGgawJ1AYZpie250bCVVFw3kIpuasnPZb8fygDOFFBOmQg2VdllbhkTpGnalG1CMlzGdjm6w+trkwWXOcXpaHW5bcMtSG8XYmVpiriqtA0IW+fvtotRazs6fAgMBAAECggEAasRhL40NJNwjDze0KD+bTrf1Chg7ZZ/ED1uRpS4q65ySKsFWTQ40hMsRhPazOdWeII+zy7Pp5kXlrcBlV3c9wrUCUr91ZRLPaJqbKqho6YTJB5scYN/UleBQWpFvwxCmlzKyW2eMob1gEbq+qHAjv1drjR0Bo/2gVjCksv2ByrU/n2xhzlDzCt4Qp0ii7xORtJke73WDeI6hNRJDm1SY9CK15DVMj+fdTNJMNyikMjktJPeN6uVKCA2HMZYcTEKj7UBQ66dRE1TQnMv648JDRmiq175OTbkroDFyYuDZCEkgI2yNn1Dt93kFhgfaAST0UKK2+77eksgqb1moOfKeCQKBgQD+fKzimAYIJyhJqVDmQae/zDz+Nc3Y7hqX3rqLKW5BopIe/HMe+yEkqBuzncOaHcRI9tiDBgNp3hGaD/EUNVFwDpKTKgdEXBhYyed4uuqtILTRSOTvg1ZSDazDM/SrXOaABz9h9Xne/pd5+90skcH+Nr2bPoSNGppftP2FRlF24wKBgQCgc0mAnzAOf3YV6v6s6MJnARbhp0hn3sr9JDkoxyRA/9J3MWYpcTIH51WVeOBU7PVJgbo/ogKr3VwzmUc97sjqYAaXA1uV4a2MnSCBbXnLDNG8iWD1+JWUhr4cRq6eKoyoZYKhq2RNCgxbAw52Bi777CCxtP1EQy8Crc+94E8aFQKBgQCKgabCyQT3aQB3XuzF9VPsgqdroDMB702P/MxAs3LrzCSFMtchNIMsZUZ2ctYjyjGrmJXscdhnxVKFLEoEuqQxPe0upYBBB3LE2FbgEbNqONPQ2ECpzyyrCgBOWbe/kJdvdQJdOXJ0GNKutJMDD+2qg3acyODxv1nn3yTgZY4vCwKBgCFY9Lzj2QQaX7ucdMQROF5aLpxFvVnBR2Ungy3Dffh4cxDM1pPkb+aOoQ4I6m8cNLrLWJ9jF7UKs+ARimoH2ABGZvg5/W4AUqa3/YqI61hVWL4bu2hD+yq8eoS7+AztgQB64JSjX5xXa0v7LaVAEcHQSNdGa6ElaX7gCx5GoYolAoGAJqqHtWCRhHPtZrqeItRAwc6F4tbvuWSeF2T1rHNM3CfTNrmPERUbx1i89Egc9LRB7qMFeIfEYUamKjIrQIgFi1IZKMO+15syeWmV3mPZ6QBemCuOqBz6fl1r3/GhdqDaS0r2H4VL3GGKKgrT+SHyTFLBzgtMFDpEIQZmw+u+lJI=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArOy70LctaepkKRx8zzY6h5pRzMwJEFDS43Jy3HRw1FZ+N9i4clDmksAghQMenXpB20TmxaGrKudkYDeDG7Y5H00IkX40ZiPCiW9uYLgV8QbbvFdClNICssQCLXgx7uAq2F3mtT7Iptxvofjz5NG1chWsfTy8etGXgBNO8ohHDlDgsOob7mtVewdldh6R0GBQPFTSYsEP65CbZyNHxPzY6hbI/wbp0Vmpufyaske+JwNJo6jfJCC/Z3l8P2eTYX+oSltw71BA55VGC3wD9qmjVgdecNxCACgiFLedAFIKn2virZ4HZ82QMkDtVe9xjxpW9TucaWmI+bGHpdrxf1+nQIDAQAB
  notifyUrl:  http://6uf8nu.natappfree.cc/alipay/notify
  returnUrl: http://localhost:8001/alipay/return




