server:
  port: 8001
spring:
  datasource:
    username: root
    password: 3418972095
    url: jdbc:mysql://localhost:3306/ordering_system?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    format:
      time: HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



  thymeleaf:
    cache: false

#整合Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml    #指定下面的xml路径
  type-aliases-package: com.shiki.entity   # 注意对应实体类的路径  配置包扫描的别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页插件
#